add replacement variables

diff --git a/zaruba-tasks/make/_base/task.zrbMake.yaml b/zaruba-tasks/make/_base/task.zrbMake.yaml
--- a/zaruba-tasks/make/_base/task.zrbMake.yaml
+++ b/zaruba-tasks/make/_base/task.zrbMake.yaml
@@ -78,6 +78,13 @@ tasks:
           echo "{{ $d.Bold }}{{ $d.Red }}Invalid _ZRB_APP_PORTS: ${_ZRB_APP_PORTS}{{ $d.Normal }}"
           exit 1
         fi
+      _validateAppCrudFields: |
+        {{ $d := .Decoration -}}
+        if [ "$("${ZARUBA_HOME}/zaruba" list validate "${_ZRB_APP_CRUD_FIELDS}")" = 0 ]
+        then
+          echo "{{ $d.Bold }}{{ $d.Red }}Invalid _ZRB_APP_CRUD_FIELDS: ${_ZRB_APP_CRUD_FIELDS}{{ $d.Normal }}"
+          exit 1
+        fi
       _setDefaultAppContainerVolumes: |
         if [ "$("${ZARUBA_HOME}/zaruba" list length "${_ZRB_APP_CONTAINER_VOLUMES}")" = 0 ]
         then
@@ -117,6 +124,7 @@ tasks:
         _ZRB_APP_TEST_COMMAND='{{ .GetConfig "appTestCommand" }}'
         _ZRB_APP_CRUD_ENTITY='{{ .GetConfig "appCrudEntity" }}'
         _ZRB_APP_CRUD_FIELDS='{{ .GetConfig "appCrudFields" }}'
+        {{ .GetConfig "_validateAppCrudFields" }}
         _ZRB_APP_EVENT_NAME='{{ .GetConfig "appEventName" }}'
         _ZRB_APP_HTTP_METHOD='{{ .GetConfig "appHttpMethod" }}'
         _ZRB_APP_MODULE_NAME='{{ .GetConfig "appModuleName" }}'
